[package]
name = "vc"
version = "0.0.1"
authors = ["Nathan Stocks <cleancut@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
